export class GuiDefine
{
	static TEMPLATE_GUI_GFXITEM			= 200;
	static TEMPLATE_GUI_TEXTITEM		= 201;

	//FILLRECT ITEM
	static FILLRECTITEM_WIDTH_INDEX		= 0;
	static FILLRECTITEM_HEIGHT_INDEX	= 1;
	static FILLRECTITEM_ALPHA_INDEX		= 2;
	static FILLRECTITEM_RED_INDEX		= 3;
	static FILLRECTITEM_GREEN_INDEX		= 4;
	static FILLRECTITEM_BLUE_INDEX		= 5;

	//GFX ITEM
	static GFXITEM_SPRITE_INDEX			= 0;
	static GFXITEM_FRAME_INDEX			= 1;
	static GFXITEM_ANIM_INDEX			= 2;

	//TEXT ITEM
	static TEXTITEM_TEXTID_INDEX		= 0;
	static TEXTITEM_TEXTSIZE_INDEX		= 1;
	static TEXTITEM_WIDTH_INDEX			= 2;
	static TEXTITEM_HEIGHT_INDEX		= 3;
	static TEXTITEM_FONT_INDEX			= 4;
	static TEXTITEM_RED_INDEX			= 5;
	static TEXTITEM_GREEN_INDEX			= 6;
	static TEXTITEM_BLUE_INDEX			= 7;
	static TEXTITEM_ALIGN_INDEX			= 8;
	static TEXTITEM_SHADOW_INDEX		= 9;
	static TEXTITEM_SHADOW_RED_INDEX	= 10;
	static TEXTITEM_SHADOW_GREEN_INDEX	= 11;
	static TEXTITEM_SHADOW_BLUE_INDEX	= 12;

	//ANCHOR
	static ANCHOR_NONE					= 0;
	static ANCHOR_LEFT					= 1;
	static ANCHOR_LEFT_TOP				= 2;
	static ANCHOR_LEFT_CENTER			= 3;
	static ANCHOR_LEFT_BOTTOM			= 4;
	static ANCHOR_RIGHT					= 5;
	static ANCHOR_RIGHT_TOP				= 6;
	static ANCHOR_RIGHT_CENTER			= 7;
	static ANCHOR_RIGHT_BOTTOM			= 8;
	static ANCHOR_TOP					= 9;
	static ANCHOR_TOP_CENTER			= 10;
	static ANCHOR_BOTTOM				= 11;
	static ANCHOR_BOTTOM_CENTER			= 12;
	static ANCHOR_HCENTER_VCENTER		= 13;
}